---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarr
namePrefix: sonarr-

resources:
  - ./sonarr.yml

components:
  - ../../components/nas-media
  - ../../components/pod-hardening
  - ../../components/tmpdirs
  - ../../components/http-route

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - sonarr.yml=gatus.yml

replacements:
  - sourceValue: sonarr.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: sonarr
