---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
        - name: redis-session
          configMap:
            name: redis-session
      containers:
        - name: app
          image: &image docker.io/library/nextcloud:33-apache@sha256:3e676af625884f4e228ac6655f51a4ea65f3a1e68f320ad23d17fccfa00d5b54
          resources:
            requests:
              memory: 100M
            limits:
              memory: 1G
          volumeMounts:
            - name: volume
              mountPath: /var/www/html
            - name: redis-session
              mountPath: /usr/local/etc/php/conf.d/redis-session.ini
              subPath: redis-session.ini
          env:
            - name: TZ
              value: America/Denver
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.beaver-cloud.xyz nextcloud-app-service.nextcloud
            - name: TRUSTED_PROXIES
              value: 127.0.0.1 10.0.0.0/8
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST
              value: nextcloud-postgres-service.nextcloud
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: 80
        - name: cron
          image: *image
          command: [/cron.sh]
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: volume
              mountPath: /var/www/html
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
