---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/kevindurb/k8s.git
      targetRevision: HEAD
      path: platform/zigbee2mqtt
  destination:
    server: https://kubernetes.default.svc
    namespace: zigbee2mqtt
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
