---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zigbee2mqtt
namePrefix: zigbee2mqtt-

resources:
  - ./deployment.yml

components:
  - ../../components/internal-http-route
  - ../../components/app-env
  - ../../components/app-http-service
  - ../../components/app-volume

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - zigbee2mqtt.yml=gatus.yml
  - name: app-env
    literals:
      - ZIGBEE2MQTT_CONFIG_PERMIT_JOIN=true
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=zigbee2mqtt
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto-service.mosquitto:1883
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyACM0
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=zstack
      - ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_FRONTEND_URL=https://zigbee2mqtt.beaver-cloud.xyz

replacements:
  - sourceValue: zigbee2mqtt.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: zigbee2mqtt
