---
tunnel: kube
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
originRequest:
  noTLSVerify: true
ingress:
  - hostname: beaver-cloud.xyz
    service: &envoy-gateway https://envoy-envoy-gateway-system-external-beaver-cloud-d9fc02f8.envoy-gateway.svc.cluster.local:443

  - hostname: '*.beaver-cloud.xyz'
    service: *envoy-gateway

  - service: http_status:404
