---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: template
namePrefix: template-

resources:
  - ./deployment.yml

components:
  - ../../components/internal-http-route
  - ../../components/external-http-route
  - ../../components/app-http-service
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - template.yml=gatus.yml

replacements:
  - sourceValue: template.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: template
