---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: template
namePrefix: template-

resources:
  - ../../bases/app-with-storage

components:
  - ../../components/http-route

images:
  - name: app-image
    newName: docker.io/traefik/whoami
    newTag: v1.11

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - template.yml=gatus.yml

replacements:
  - sourceValue: template.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: template
