---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole
namePrefix: pihole-

resources:
  - ./pihole.yml

components:
  - ../../components/internal-http-route
  - ../../components/app-http-service

replacements:
  - sourceValue: pihole.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - pihole.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: pihole
