---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: zfs-exporter-
namespace: zfs-exporter

resources:
  - ./zfs-exporter.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: zfs-exporter
