---
exclude: ^test/snapshots/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v26.3.0
    hooks:
      - id: ansible-lint

  - repo: local
    hooks:
      - id: snapshot-test
        name: kustomize snapshot test
        entry: just test/test-all
        language: system
        pass_filenames: false
        always_run: true
