---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tsidp
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: https://github.com/kevindurb/k8s.git
      targetRevision: HEAD
      path: platform/tsidp
  destination:
    server: https://kubernetes.default.svc
    namespace: tsidp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      prune: false
      selfHeal: true
