FROM ghcr.io/ublue-os/ucore-minimal:stable-nvidia

ARG TARGETARCH

COPY ./files/k3s-1.33.1-$TARGETARCH /usr/local/bin/k3s
COPY ./files/install-k3s.sh /opt/install.sh
COPY ./files/k3s-selinux-1.6-1.coreos.noarch.rpm /tmp

RUN dnf install -y \
  container-selinux \
  policycoreutils \
  selinux-policy \
  /tmp/k3s-selinux-1.6-1.coreos.noarch.rpm \
  && dnf clean all

RUN rm /tmp/k3s-selinux-1.6-1.coreos.noarch.rpm

ADD ./files/modules.conf /etc/modules-load.d/k8s.conf
ADD ./files/sysctl.conf /etc/sysctl.d/k8s.conf

RUN dnf remove -y \
  zram-generator-defaults

RUN systemctl disable firewalld \
    && systemctl enable tailscaled
