---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      targetRevision: 1.11.3
      chart: longhorn
      helm:
        valuesObject:
          defaultSettings:
            createDefaultDiskLabeledNodes: true
            upgradeChecker: false
          persistence:
            defaultClass: false
            dataEngine: v1
          ingress:
            enabled: true
            ingressClassName: tailscale
            host: longhorn
            tls: true
            annotations:
              tailscale.com/proxy-group: ingress-proxy-group
              tailscale.com/tags: tag:k8s
          longhornManager:
            serviceAnnotations:
              prometheus.io/scrape: 'true'
              prometheus.io/port: '9500'
    - repoURL: https://github.com/kevindurb/k8s.git
      targetRevision: HEAD
      path: infrastructure/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      prune: false
      selfHeal: true
