---
userDefaults:
  singleClick: true
  stickySidebar: false
server:
  port: 80
  database: /config/database.db
  cacheDir: /tmp
  sources:
    - path: /media
      name: media
      config:
        defaultEnabled: true
auth:
  methods:
    noauth: true
    password:
      enabled: false
    proxy:
      enabled: false
      header: Remote-User
      createUser: true
