---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://democratic-csi.github.io/charts/
      targetRevision: 0.15.1
      chart: democratic-csi
      helm:
        valuesObject:
          csiDriver:
            name: "org.democratic-csi.nvmeof"
          storageClasses:
            - name: zfs-generic-nvmeof-csi
              defaultClass: true
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                fsType: ext4
              mountOptions: []
              secrets:
                provisioner-secret:
                controller-publish-secret:
                node-stage-secret:
                node-publish-secret:
                controller-expand-secret:
          volumeSnapshotClasses:
            - name: zfs-generic-nvmeof-csi
              parameters:
              secrets:
                snapshotter-secret:
          driver:
            existingConfigSecret: democratic-csi-driver-config-sealed
            config:
              driver: zfs-generic-nvmeof
    - repoURL: https://github.com/kevindurb/k8s.git
      targetRevision: HEAD
      path: infrastructure/democratic-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      prune: true
      selfHeal: true
