# SPDX-License-Identifier: MIT-0
---
- name: Drain node
  delegate_to: localhost
  ansible.builtin.command:
    cmd: >
      kubectl drain
      --delete-emptydir-data
      --ignore-daemonsets
      {{ ansible_hostname }}
  changed_when: false

- name: Stop k3s service
  become: true
  ansible.builtin.systemd_service:
    name: '{{ (k3s_role == "agent") | ternary("k3s-agent.service", "k3s.service") }}'
    state: stopped

- name: Reboot node
  become: true
  ansible.builtin.reboot:

- name: Ensure k3s is running
  become: true
  ansible.builtin.systemd_service:
    name: '{{ (k3s_role == "agent") | ternary("k3s-agent.service", "k3s.service") }}'
    state: started

- name: Uncordon node
  delegate_to: localhost
  kubernetes.core.k8s_drain:
    state: uncordon
    name: '{{ ansible_hostname }}'
