---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud
namePrefix: nextcloud-

resources:
  - ./deployment.yml
  - ./postgres.yml
  - ./valkey.yml

components:
  - ../../components/http-route-refs
  - ../../components/bitwarden-secret-name-reference
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs

configMapGenerator:
  - name: redis-session
    options:
      labels:
        app.kubernetes.io/component: app
    files:
      - ./redis-session.ini
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - nextcloud.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: nextcloud
