---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud
namePrefix: nextcloud-

resources:
  - ../../bases/postgres
  - ../../bases/app-with-storage

components:
  - ../../components/http-route

patches:
  - path: ./app-deployment.patch.yml
    target:
      kind: Deployment
      name: app-deployment

replacements:
  - sourceValue: nextcloud.beaver-cloud.xyz
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
          - spec.tls.0.secretName
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0
  - sourceValue: 10G
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: app-volume
        fieldPaths:
          - spec.resources.requests.storage
  - sourceValue: /var/www/html
    targets:
      - select:
          kind: Deployment
          name: app-deployment
        fieldPaths:
          - spec.template.spec.containers.0.volumeMounts.[name=volume].mountPath

configMapGenerator:
  - files:
      - nextcloud.yml=gatus.yml
    name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: nextcloud
