---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: &labels
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
        - name: app
          image: ghcr.io/go-vikunja/vikunja:2
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: TZ
              value: America/Denver
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: https://vikunja.beaver-cloud.xyz
            - name: VIKUNJA_SERVICE_ROOTPATH
              value: /config
            - name: VIKUNJA_DATABASE_PATH
              value: /config/vikunja.db
            - name: VIKUNJA_SERVICE_ENABLEREGISTRATION
              value: 'false'
            - name: VIKUNJA_FILES_BASEPATH
              value: /config/files
          resources:
            requests:
              memory: 128M
            limits:
              memory: 256M
          ports:
            - name: http
              containerPort: 3456

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels: &labels
    app.kubernetes.io/component: app
spec:
  selector: *labels
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: internal-route
  annotations:
    internal-dns.alpha.kubernetes.io/target: internal.beaver-cloud.xyz
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal-beaver-cloud
      namespace: envoy-gateway-system
  hostnames:
    - vikunja.beaver-cloud.xyz
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ''
          kind: Service
          name: app-service
          port: 80
          weight: 1

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-route
  annotations:
    external-dns.alpha.kubernetes.io/target: external.beaver-cloud.xyz
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-beaver-cloud
      namespace: envoy-gateway-system
  hostnames:
    - vikunja.beaver-cloud.xyz
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ''
          kind: Service
          name: app-service
          port: 80
          weight: 1
