---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome
namePrefix: navidrome-
resources:
  - ./deployment.yml
components:
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs
  - ../../components/nas-media

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - navidrome.yml=gatus.yml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: navidrome
