---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: makemkv
namePrefix: makemkv-

resources:
  - ../../bases/app

components:
  - ../../components/app-nas-media
  - ../../components/internal-http-route
  - ../../components/app-env
  - ../../components/privileged-app

images:
  - name: app-image
    newName: jlesage/makemkv
    newTag: v26.01.2@sha256:4c114cfbd0ba7feef85c72d1721b8ea13a44ebc010b4996b644e618906e61717

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - makemkv.yml=gatus.yml
  - name: app-env
    literals:
      - MAKEMKV_KEY=T-URt6MHxNy3HmfVojU8pE05WQ6HfgVI8S@HiIeNcWFim9rBgNlOdLFROSATCsWikcKW
      - USER_ID=1000
      - GROUP_ID=1000
      - SUP_GROUP_IDS=11
      - TZ=America/Denver
      - DARK_MODE=1
      - AUTO_DISC_RIPPER=1
      - AUTO_DISC_RIPPER_EJECT=1
      - AUTO_DISC_RIPPER_MIN_TITLE_LENGTH=600 # 10 minutes
      - AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR=1

replacements:
  - sourceValue: '5800'
    targets:
      - select: &app-deployment
          kind: Deployment
          name: app-deployment
        fieldPaths:
          - spec.template.spec.containers.[name=app].ports.[name=http].containerPort

  - sourceValue: makemkv.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: drone-04
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0
        value:
          name: nas-media
          mountPath: /output
          subPath: Downloads
    target: *app-deployment

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: makemkv
