---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: makemkv
namePrefix: makemkv-

resources:
  - ./deployment.yml

components:
  - ../../components/http-route-refs
  - ../../components/nas-media
  - ../../components/app-tmp-dirs

configMapGenerator:
  - name: hooks
    files:
      - ./hooks/send_email.sh
      - ./hooks/automatic_disk_ripper_started.sh
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - makemkv.yml=gatus.yml
  - name: app-env
    literals:
      - INSTALL_PACKAGES=curl bash
      - UMASK=000
      - MAKEMKV_KEY=BETA
      - USER_ID=1000
      - GROUP_ID=1000
      - SUP_GROUP_IDS=11
      - TZ=America/Denver
      - DARK_MODE=1
      - AUTO_DISC_RIPPER=1
      - AUTO_DISC_RIPPER_EJECT=1
      - AUTO_DISC_RIPPER_MIN_TITLE_LENGTH=600 # 10 minutes
      - AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR=1

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: makemkv
