---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: makemkv
namePrefix: makemkv-

resources:
  - ./deployment.yml

components:
  - ../../components/nas-media
  - ../../components/internal-http-route
  - ../../components/app-http-service
  - ../../components/app-tmp-dirs

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - makemkv.yml=gatus.yml
  - name: app-env
    literals:
      - MAKEMKV_KEY=T-sJ5R5BKxhD671U9s0teXbyP19MhCkkkB7rmnNbb1aEHaqveiVqyI3RXGMHDXhoyNUC
      - USER_ID=1000
      - GROUP_ID=1000
      - SUP_GROUP_IDS=11
      - TZ=America/Denver
      - DARK_MODE=1
      - AUTO_DISC_RIPPER=1
      - AUTO_DISC_RIPPER_EJECT=1
      - AUTO_DISC_RIPPER_MIN_TITLE_LENGTH=600 # 10 minutes
      - AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR=1

replacements:
  - sourceValue: makemkv.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: makemkv
