---
configuration:
  working_directory: /media/.ytdl-sub-working-directory
presets:
  Music:
    preset:
      - YouTube Releases
      - Max Audio Quality
    overrides:
      music_directory: /media/Music
