---
TV Show:
  3Blue1Brown: https://www.youtube.com/@3blue1brown
  Action Retro: https://www.youtube.com/@ActionRetro
  Adam Neely: https://www.youtube.com/@AdamNeely
  Aging Wheels: https://www.youtube.com/@agingwheels
  Amanda Outside: https://www.youtube.com/@amanda.outside
  Ambition Strikes: https://www.youtube.com/@AmbitionStrikes
  Auto Focus: https://www.youtube.com/@AutoFocus
  Backcountry Exposure: https://www.youtube.com/@BackcountryExposure
  Berm Peak: https://www.youtube.com/@SethsBikeHacks
  BibleProject: https://www.youtube.com/@bibleproject
  Billet Labs: https://www.youtube.com/@BilletLabs
  Brick Experiment Channel: https://www.youtube.com/@BrickExperimentChannel
  Blacktail Ranch: https://www.youtube.com/@BlacktailRanch
  Blacktail Studio: https://www.youtube.com/@BlacktailStudio
  Blacktail Studio Uncut: https://www.youtube.com/@blacktailstudiouncut
  Bringus Studios: https://www.youtube.com/@BringusStudios
  Cameron Grey: https://www.youtube.com/@camerongray1515
  CGP Grey: https://www.youtube.com/@CGPGrey
  Cleo Abram: https://www.youtube.com/@CleoAbram
  Craft Computing: https://www.youtube.com/@CraftComputing
  Dan Becker: https://www.youtube.com/@DanBecker
  David Rule: https://www.youtube.com/@davidmrule
  Drew Builds Stuff: https://www.youtube.com/@DrewBuildsStuff
  Garage Grown Gear: https://www.youtube.com/@garagegrowngear
  Geerling Engineering: https://www.youtube.com/@GeerlingEngineering
  Go4x4: https://www.youtube.com/@go4x4media
  Hannah Fry: https://www.youtube.com/@fryrsquared
  Hardware Haven: https://www.youtube.com/@HardwareHaven
  Hike, Camp, Cook: https://www.youtube.com/@HikeCampCook
  Howtown: https://www.youtube.com/@Howtown
  I Like To Make Stuff: https://www.youtube.com/@Iliketomakestuff
  Interfacing Linux: https://www.youtube.com/@InterfacingLinux
  Jakkuh: https://www.youtube.com/@jakkuh_t
  James Hoffmann: https://www.youtube.com/@jameshoffmann
  Jeff Geerling: https://www.youtube.com/@JeffGeerling
  JerryRigEverything: https://www.youtube.com/@JerryRigEverything
  Jon Bringus: https://www.youtube.com/@JonBringus
  Justin Outdoors: https://www.youtube.com/@JustinOutdoors
  Justinthetrees: https://www.youtube.com/@Justinthetrees
  Level 2 Jeff: https://www.youtube.com/@Level2Jeff
  Linus Tech Tips: https://www.youtube.com/@LinusTechTips
  Made With Layers: https://www.youtube.com/@MadeWithLayers
  Make Something: https://www.youtube.com/@MakeSomething
  Malcolm Guite: https://www.youtube.com/@MalcolmGuitespell
  Marius Hornberger: https://www.youtube.com/@MariusHornberger
  Matt DAvella: https://www.youtube.com/@mattdavella
  Matt Spears: https://www.youtube.com/@MattSpears
  Mark Rober: https://www.youtube.com/@MarkRober
  Matt Whitman and The Ten Minute Bible Hour: https://www.youtube.com/@MattWhitmanTMBH
  Matthias Random Stuff: https://www.youtube.com/@matthiasrandomstuff2221
  Matthias Wandel: https://www.youtube.com/@matthiaswandel
  MattKC: https://www.youtube.com/@MattKC
  MH Anything: https://www.youtube.com/@MHAnything
  Michael MJD: https://www.youtube.com/@MichaelMJD
  Mike Boyd: https://www.youtube.com/@MikeBoyd
  Minute Earth: https://www.youtube.com/@MinuteEarth
  Minute Food: https://www.youtube.com/@MinuteFood
  Minute Physics: https://www.youtube.com/@MinutePhysics
  Miranda Goes Outside: https://www.youtube.com/@MirandaGoesOutside
  My Life Outdoors: https://www.youtube.com/@MyLifeOutdoors
  My Mechanics Insights: https://www.youtube.com/c/mymechanicsinsights
  My Mechanics: https://www.youtube.com/@mymechanics
  Nate From the Internet: https://www.youtube.com/@NFTI
  NetworkChuck: https://www.youtube.com/@NetworkChuck
  No Boilerplate: https://www.youtube.com/@NoBoilerplate
  Oscar Hikes: https://www.youtube.com/@OscarHikes
  Oscar Hikes V2: https://www.youtube.com/@oscarhikesv2
  Outdoor Boys: https://www.youtube.com/@OutdoorBoys
  Outdoor Tom: https://www.youtube.com/@outdoortom9675
  Paul Messner: https://www.youtube.com/@PaulMessner
  Practical Engineering: https://www.youtube.com/@PracticalEngineeringChannel
  Playing with Sticks: https://www.youtube.com/@PlayingwithSticks
  Quiet Nerd: https://www.youtube.com/@QuietNerd
  Raid Owl: https://www.youtube.com/@RaidOwl
  Rainfall Projects: https://www.youtube.com/@rainfallprojects501
  rctestflight: https://www.youtube.com/@rctestflight
  Sauce+: https://www.youtube.com/@sauceplusofficial
  Set To Hike: https://www.youtube.com/@settohike
  SmarterEveryDay: https://www.youtube.com/@smartereveryday
  SmarterEveryDay2: https://www.youtube.com/@smartereveryday2
  Snazzy Labs: https://www.youtube.com/@snazzy
  Speeed: https://www.youtube.com/@SpeeedCo
  Stand-up Maths: https://www.youtube.com/@standupmaths
  Steve Mould: https://www.youtube.com/@SteveMould
  Strange Parts: https://www.youtube.com/@StrangeParts
  Stuff Made Here 2: https://www.youtube.com/@StuffMadeHere2
  Stuff Made Here: https://www.youtube.com/@StuffMadeHere
  TechLinked: https://www.youtube.com/@techlinked
  Technology Connections: https://www.youtube.com/@TechnologyConnections
  Technology Connextras: https://www.youtube.com/@TechnologyConnextras
  The Adventure Addicts | Zoe & Kelby: https://www.youtube.com/@the_adventureaddicts
  The Adventures of Victor Bart: https://www.youtube.com/@victorbartadventures
  The Rest Is Science: https://www.youtube.com/@TheRestIsScience
  The Stock Pot: https://www.youtube.com/@TheStockPot-AU
  The Saucepan: https://www.youtube.com/@TheSaucepan-AU
  The Slow Mo Guys: https://www.youtube.com/@theslowmoguys
  This Does Not Compute: https://www.youtube.com/@ThisDoesNotCompute
  thruhikers: https://www.youtube.com/@reneeandtim
  Tim Station: https://www.youtube.com/@TimStation
  Tom Stanton: https://www.youtube.com/@TomStantonEngineering
  Tom Scott: https://www.youtube.com/@TomScottGo
  Tom Scott Plus: https://www.youtube.com/@tomscottplus
  Under Dunn: https://www.youtube.com/@UnderDunnOfficial
  Valve: https://www.youtube.com/@Valve
  Veritasium: https://www.youtube.com/@veritasium
  Woodbrew: https://www.youtube.com/@Woodbrew
  Woodsbound Outdoors: https://www.youtube.com/@WoodsboundOutdoors
  YNAB: https://www.youtube.com/@YNABofficial
  Zip Tie Tech: https://www.youtube.com/@zip_tie_tech
  Zip Tie Tuning: https://www.youtube.com/@ZipTieTuning
  xkcd's What If?: https://www.youtube.com/@xkcd_whatif

TV Show Collection:
  = Tutorials:
    ~Event Lightning:
      s01_name: GrandMA 3 Tutorials
      s01_url: https://www.youtube.com/playlist?list=PLhh6ZoFPnUu1hMCDT2YhuYJxLgW_G0rTn
    ~Aria Hailey:
      s01_name: Phaser Friday
      s01_url: https://www.youtube.com/playlist?list=PLcl55cI1T_GxbwcgzPTvrOZ0-3Gp6_ApB
      s02_name: Timing Tuesday
      s02_url: https://www.youtube.com/playlist?list=PLcl55cI1T_GxPad4tGmZG2lGhtArrI2WX
  = Christian:
    ~The Promised Land:
      s01_name: Season 1
      s01_url: https://www.youtube.com/playlist?list=PLaKYsaAeVpIaO4QGF41-ZvvuG6rPqYPI3
  = Kids:
    ~Bumble Nums:
      s01_name: Season 1
      s01_url: https://www.youtube.com/playlist?list=PLu5x8wTdwBhET1uXa2LT0x6gM26Y8_9Yg
      s02_name: Season 2
      s02_url: https://www.youtube.com/playlist?list=PLu5x8wTdwBhEwC6IRWQ-SeelJzOa9tVdc
