---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus
namePrefix: prometheus-

resources:
  - ./prometheus.yml

components:
  - ../../components/pod-hardening
  - ../../components/http-route

replacements:
  - sourceValue: prometheus.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

configMapGenerator:
  - name: config
    files:
      - ./config/prometheus.yml
  - name: rules
    files:
      - ./config/rules/rules.yml
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - prometheus.yml=gatus.yml

commonLabels:
  app.kubernetes.io/name: prometheus
