---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus
namePrefix: prometheus-

resources:
  - ./prometheus.yml
  - ./rbac.yml

components:
  - ../../components/app-pod-hardening
  - ../../components/internal-http-route
  - ../../components/app-http-service
  - ../../components/prometheus-scrape-app-service
  - ../../components/app-volume

replacements:
  - sourceValue: prometheus.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0
  - sourceValue: 35Gi
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: app-volume
        fieldPaths:
          - spec.resources.requests.storage

configMapGenerator:
  - name: config
    files:
      - ./config/prometheus.yml
  - name: rules
    files:
      - ./config/rules/rules.yml
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - prometheus.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: prometheus
