---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh-interval: '6h'
spec:
  project: default
  sources:
    - chart: gateway-helm
      repoURL: docker.io/envoyproxy
      targetRevision: 1.7.4
    - repoURL: https://github.com/kevindurb/k8s.git
      targetRevision: HEAD
      path: platform/envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
