---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wireguard
namePrefix: wireguard-

resources:
  - ../../bases/app-with-storage
  - ./dns-endpoint.yml

components:
  - ../../components/app-env

images:
  - name: app-image
    newName: lscr.io/linuxserver/wireguard
    newTag: latest

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - wireguard.yml=gatus.yml
  - name: app-env
    literals:
      - PEERS=workmac,corella
      - PUID=1000
      - PGID=1000
      - PEERDNS=192.168.42.53
      - INTERNAL_SUBNET=10.100.100.0
      - ALLOWEDIPS=10.100.100.0/24,192.168.0.0/16
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=true
      - SERVERURL=home.beaver-cloud.xyz

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value:
          fsGroup: 1000
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          readOnlyRootFilesystem: true
          capabilities:
            add: [NET_ADMIN]
      - op: replace
        path: /spec/template/spec/containers/0/ports/0
        value:
          name: wg
          protocol: UDP
          containerPort: 51820
    target:
      kind: Deployment
      name: app-deployment
  - patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.42.7
      - op: replace
        path: /spec/ports/0
        value:
          name: wg
          protocol: UDP
          port: 51820
          targetPort: wg
    target:
      kind: Service
      name: app-service

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: wireguard
