---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wireguard
namePrefix: wireguard-

resources:
  - ../../bases/app-with-storage

components:
  - ../../components/app-env

images:
  - name: app-image
    newName: lscr.io/linuxserver/wireguard
    newTag: latest

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - wireguard.yml=gatus.yml
  - name: app-env
    literals:
      - PEERS=workmac,corella
      - PUID=1000
      - PGID=1000

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value:
          fsGroup: 1000
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          readOnlyRootFilesystem: true
          capabilities:
            add: [NET_ADMIN]
    target:
      kind: Deployment
      name: app-deployment

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: wireguard
