---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgDb6uGFXQ7m4ARDnjU6CEziQ/HlTzeG73v10TiNYZhWKB4WVWghMRmF15Cnx8ybbD3cc6HiKhrsLampnHOSxVPP7lMWqXUJkbyW2GtNumH+XiXGF6CYzW+35diGsfmTah2mq/1sHbSahqsq+AUuUrIh+PULDaBqg4VySpXOnKyg9VlsGZcUbC+rw+WhO4NoOfDbzNWDKNGk4Yy6LjwAG6Hh3hNoTdTgraE0syCQI8oieE6P3hpgb/ZdjnXnOkrQPJ6eVAK/rcpjHIA6QN7/7WU16B5Bo4xdsuMXo9+EbD/ZT/Ka7tdbs1fqwmbz7LJr1ms/V443Lf3uZnRd04JzOlbjnNsaDsf78kdDmaIpQXF9OABNyeAj+P/2U4Ua3bB9lrKUKmHZU0qeg3tW7LnPfOcPODRJNbUFIsgIjZ5zdCGLh5w/OnAqt7sJZzcjyquX5/KR1OGLOKvnlIAd6eDcteKoNrJo0L7kmvnt+6nCHrOoSGf0UJmIdyRjGFU2qEHjRRU8XZ5g9pVsWZLCzGo1NDl/S7ptofV3WJzl7L1CSZjY5r2LidajiT2Mnl9RhY8ObZfyGj8LLeQ/7lRLWUj6To42mVyzh1cqyzd2XDpMHeziyjq6cvwTiwB2MeCWh5yGttSwBGF3eYd3S5xJ0ZA8za1hslf7QfCJAldBhSLeTeKK6n70R49TAoJTMdQ5mZiCKJ6qHpzA0wSrV2yesW26VBmHApZ9sIUapS4y1H2osEhXc2PURk2Mk6zNir45ZcWg+THCB/HIJXUxA95FMIpEcoNn
  template:
    metadata:
      name: searxng-secret
      namespace: searxng
