---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    tailscale.com/proxy-group: ingress-proxy-group
spec:
  defaultBackend:
    service:
      name: argocd-server
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts: [argocd]
