---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

components:
  - ../../components/http-route

replacements:
  - sourceValue: argocd.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0
  - sourceValue: argocd-server
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.rules.0.backendRefs.0.name

patches:
  - path: ./resources/config.patch.yml
  - path: ./resources/metrics-service.patch.yml
  - path: ./resources/argocd-server.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - argocd.yml=gatus.yml
