---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared
namePrefix: cloudflared-

resources:
  - ./cloudflared.yml

components:
  - ../../components/app-pod-hardening
  - ../../components/app-http-service

configMapGenerator:
  - name: config
    files:
      - ./config/config.yml
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - alertmanager.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: cloudflared
