---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./bws-operator/app.yml
  - ./mosquitto/app.yml
  - ./sealed-secrets/app.yml
  - ./smtp-relay/app.yml
  - ./tsidp/app.yml
  - ./zigbee2mqtt/app.yml
