---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./bws-operator/app.yml
  - ./cert-manager/app.yml
  - ./envoy-gateway/app.yml
  - ./smtp-relay/app.yml
  - ./wireguard/app.yml
  - ./zigbee2mqtt/app.yml
