---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-pod
namePrefix: dev-pod-

resources:
  - ./deployment.yml
  - ./rbac.yml

components:
  - ../../components/http-route-refs
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs

patches:
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=app
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroupChangePolicy
        value: OnRootMismatch

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: dev-pod
