---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: healthchecks
spec:
  encryptedData:
    PING_KEY: AgDHUv+zBCb3MyG/JXHhCvSmudNGqICuz0ByNLj44+MCvAD7q8IBO0HLVdzL1WRtYXgKca8ZLnK60icOXjw74Uw+PyIlN+MWBrS339ljFlzc/tVaAmWiWJvKCzcPpBtP9NDPSoSNKpvbIkHMrzR52BHlhVrPgqO11ZneZ3AJWEXsWTtHag3ErYt4MlHVWYRorUobUBdZ6xe3kEfGZkgSkBbCS62LqwRgG1RQAPnCyKFwQuEb18LIM1q2ZxnBN8xqHf2cXgDkpRSGexaLK2pGCbkkwevk45sehl/vEPKlUZlskfNDUBzN5UUMKhmh0kP89/765TQyQ7I4ea/W54VgOaBbxlorta3Jpi6P65x3b3fEayIVOUvTKKaDNvKx8BxWB95efuzLC0jttOEaa4+d/OIPnPWt2LlU48B34Qsr2wPMMoDPx+BvYrj7gjIssP4ui/cEi+T4x9FFigW6D4x0ZIKmFj1D9k0mXBcM9FWyIJ1kSYK64xvJjdQg4Wwxgh+x0PlRIeU1/CsA7lEDNGMPBHu1hKOkxrk6+co40dQ+1obOCTnMmCNgUpYx0h2yoFfTuaI0o/emdEvY8/v2lk4N6jhqMhAJg45iUxnUl3J9wbvZteylA4BMp8iuOhJjeqZW0iqxRpZ3Yc5y1mNQfgnNkNzn9Jc5A6dCmFB3mMRu4CrVcQvQWhfIQsYynDazmlQVULw+M1hmdjSiFAgkeG1lTpgo8xM8CFRj
