---
metrics: true

endpoints:
  - name: gatus
    url: http://gatus-service
    conditions: ['[STATUS] == 200']

  - name: google
    url: https://google.com
    conditions: ['[STATUS] == 200']

  - name: router
    url: https://192.168.1.1
    group: networking
    client: { insecure: true }
    conditions: ['[STATUS] == 200']

  - name: Garage AP
    url: http://192.168.1.2
    group: networking
    conditions: ['[STATUS] == 200']

  - name: Basement AP
    url: http://192.168.1.3
    group: networking
    conditions: ['[STATUS] == 200']

  - name: Backyard AP
    url: http://192.168.1.4
    group: networking
    conditions: ['[STATUS] == 200']
