---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels: &labels
    app.kubernetes.io/component: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.product: Quadro-P620-SHARED
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
      containers:
        - name: scrypted
          image: ghcr.io/koush/scrypted:v0.144.1-noble-nvidia@sha256:da86752279289444ba093caf908c2534abbdf134058143755cd0b085bd88b47c
          resources:
            requests:
              memory: 100M
            limits:
              nvidia.com/gpu: '1'
              memory: 4G
          volumeMounts:
            - name: volume
              mountPath: /server/volume
          env:
            - name: TZ
              value: America/Denver
          ports:
            - name: http
              containerPort: 11080

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 10G

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
