---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: &labels
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      volumes:
        - name: config-map
          configMap:
            name: config
        - name: cache
          emptyDir: {}
      containers:
        - name: smtp-relay
          image: ghcr.io/foxcpp/maddy:0.7.1@sha256:6ab538e2f28baf2324f7cb418c7f9476fd9c7e9fa9b14bc3aecf51a9f6962064
          resources:
            requests:
              memory: 50M
            limits:
              memory: 100M
          volumeMounts:
            - name: config-map
              mountPath: /data/maddy.conf
              subPath: maddy.conf
              readOnly: true
            - name: cache
              mountPath: /cache
          envFrom:
            - secretRef:
                name: smtp-relay-secret
          env:
            - name: SMTP_RELAY_SMTP_PORT
              value: '25'
            - name: SMTP_RELAY_METRICS_PORT
              value: '8080'
          ports:
            - name: smtp
              containerPort: 25

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels: &labels
    app.kubernetes.io/component: app
spec:
  selector: *labels
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
