---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.102.3
      chart: tailscale-operator
      helm:
        valuesObject:
          apiServerProxyConfig:
            allowImpersonation: true
    - repoURL: https://github.com/kevindurb/k8s.git
      targetRevision: HEAD
      path: infrastructure/tailscale
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      prune: false
      selfHeal: true
