---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ts-auth-key
  namespace: qbittorrent
spec:
  encryptedData:
    TS_AUTHKEY: AgCLUK6Oa6vrvb7GszaIVRycRh4bVujcoQDa3MztG8RSsHP8juAeebdLUj+OSOpJ4lUi1qXQcQu3OHfNGf8+rC6AHKPoErjjonkL/NdF1laApHD1nKIVyaqUVxPFT6K6Df5hbx7ofPKdTKI8+0uyn5oQtJ/agAWyse3MabsV/WdtYkJ6XHynaha8AYfZXibLZeTthdRiABx6VWoPBoY1fxnRi1QQUuRbs4u3uizAXSrjJG3sUMCZB95GX1IFzVn064cfRfTUukLdUN2xx93jwb5n73/Qa7DyI+QeMrJCMN+sQbL73YJYnNicbz8xZ/2Yu+qr9SX3FMvsMLxKdBLyc06sEkXvFEY4N842VGSMtJuKfN0+7TxeYm4tZiw3+mbIu6oA5EMrxdXaYpfKuXOIB4rhN/fGtaGF0jkGFoSA1uepeaRRvCaAMNG0jyQohKyEAilsDqimEgf6tTmUh5quidhyAVc8D7Trjc6aO5cG2btdasggelyXnVAti5zcpIyBngll8iTNBYS+amrmnAl7ATk0UDlqBZOO5Y2qMQtpm6Cum+PNKJwjbWJXOmzIBxL6ZoCYnPKo2knKXMXpi6h3tv7FlJWOssSewNmmxUVe64wK0vy/6GuarKesgNMypoY4sHwMfHmv8fj4J6VddO2fb3uKieep01LXVKniZQ3VWLefeNkH4Y1vI8qYn7xe0nbWIpwURUx0B6M01xB49hPAIDYzn0nL5ZcgbAGMMJNZM32ic74IMrUj7uA3+JWsypbyH+hByLCahZP6RSJXd4dM
