---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: filebrowser
namePrefix: filebrowser-

resources:
  - ./deployment.yml

components:
  - ../../components/app-nas-media
  - ../../components/internal-http-route
  - ../../components/app-http-service
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs
  - ../../components/app-volume

configMapGenerator:
  - name: config
    files:
      - ./config/config.yaml
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - filebrowser.yml=gatus.yml

replacements:
  - sourceValue: filebrowser.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: filebrowser
