[rust/media]
use_template = production
recursive = no

[rust/longhorn]
use_template = backups
recursive = no

[template_production]
frequently = 0
hourly = 36
daily = 30
weekly = 8
monthly = 6
yearly = 0
autosnap = yes
autoprune = yes

[template_backups]
frequently = 0
hourly = 0
daily = 7
weekly = 2
monthly = 0
yearly = 0
autosnap = yes
autoprune = yes
