---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: postgres-

resources:
  - ./postgres.yml

components:
  - ../../components/pod-hardening
  - ../../components/tmpdirs
  - ../../components/bitwarden-secret-name-reference

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: postgres
