---
apiVersion: v1
kind: Pod
metadata:
  name: cookie-loader
  namespace: ytdl-sub
spec:
  restartPolicy: Never
  containers:
    - name: cookie-loader
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: config
          mountPath: /config
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: ytdl-sub-config
