default:
  @just --list

load-cookie path:
  #!/usr/bin/env bash
  set -euo pipefail
  cookie_path="{{ invocation_directory() / path }}"
  trap 'kubectl delete -f cookie-loader.yml --ignore-not-found' EXIT

  kubectl apply -f cookie-loader.yml
  kubectl wait -n ytdl-sub --for=condition=Ready pod/cookie-loader --timeout=60s
  kubectl cp "$cookie_path" ytdl-sub/cookie-loader:/config/cookie.txt
