---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ytdl-sub
namePrefix: ytdl-sub-
resources:
  - ./cronjob.yml
components:
  - ../../components/http-route-refs
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs
  - ../../components/nas-media
configMapGenerator:
  - name: config
    files:
      - ./config/config.yml
      - ./config/subscriptions.yml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: ytdl-sub
