---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: miniflux
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCrdRuBHV+dHmEBS07idL8YImSv++mbitxlgGN8ToqzhkYRamRZCrLshttX+s1dvV+3VmbwfGcFGNOI0ksM5hjZvKURc+58NLTPIpmdPd7d4ssAeMMLjiPjAF0wyqca3/aOxwbdnbfaX6q+0GORocht3GIqsSkQPOhmH0DR6rykUkzuTTatT6HLOAh5s3U0p7Oxtj3hIjoAIpUORLASVVAGyLwYGt+UD4kV8XUDTlK4m9TBb4o1mRmACPadE7Mcu2/QIiBhAII8ivEP+EUHymoMRxzoBkaT3ze97ee7xwTd1DSnlz05e+kMi4Gbbkk5JkKb8f5EvScp+JJinZ45seXOq2k32wNak4XE8oYU8qMwQT0dbOAx35HoL65kase2HZ+yqL4Ynru7qZmtBPuuk8zPZHRWg0xc9LEa+FHSuDxLGWtvVffdWGa26ItzEKwIUkTDd6/y6y9AkLUwAqiY4rcc1pWAwZxarYwh5a2HugoppPqF2mZ8zivia7HWjIkaIG9aY9ZEicLc3i95SGtvTfH9b8MpU5wfpO7XzCaUkggNaXvjNJFLXfEfYkvOyrnXnfDPp3/THHhETmZnNhpJEwOPO/PUvzIsX+WmgCUlMeQZVi3974PQI89VAwtj7EaL1yCHCvT6JOLu+VVs25pT4SmJYBKS0ZvEIHeQloOPlKqb0jpFC3KvZ5TrRq2BHIir0ZtSTgYSVvuzFiLyBTNp3jAnEZMXqg==
