---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatus
namePrefix: gatus-

resources:
  - ../../bases/app-with-storage
  - ./rbac.yml

images:
  - name: app-image
    newName: ghcr.io/twin/gatus
    newTag: v5.34.0

configMapGenerator:
  - name: config
    files:
      - ./config/gatus.yml

replacements:
  - sourceValue: gatus.beaver-cloud.xyz
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
          - spec.tls.0.secretName

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: config-map
          configMap:
            name: config
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: config-map
          mountPath: /config/config.yaml
          subPath: config.yaml
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: GATUS_LOG_LEVEL
            value: DEBUG
          - name: GATUS_CONFIG_PATH
            value: /config
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 100M
          limits:
            memory: 500M
      - op: add
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: service-account
    target:
      kind: Deployment
      name: app-deployment
  - path: ./k8s-sidecar.patch.yml
    target:
      kind: Deployment
      name: app-deployment

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: gatus
