---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatus
namePrefix: gatus-

resources:
  - ./deployment.yml
  - ./rbac.yml

components:
  - ../../components/internal-http-route
  - ../../components/app-env
  - ../../components/app-http-service
  - ../../components/app-volume
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs

configMapGenerator:
  - name: config
    files:
      - ./config/gatus.yml
  - name: app-env
    literals:
      - GATUS_LOG_LEVEL=DEBUG
      - GATUS_CONFIG_PATH=/config

replacements:
  - sourceValue: gatus.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: gatus
