---
apiVersion: batch/v1
kind: Job
metadata:
  name: PLACEHOLDER
  namespace: transcoding
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: drone-04
      tolerations:
        - {key: dedicated, operator: Equal, value: storage, effect: NoSchedule}
      volumes:
        - name: nas-media
          persistentVolumeClaim: {claimName: nas-media}
      containers:
        - name: handbrake
          image: ghcr.io/kevindurb/handbrake-cli:latest@sha256:6a62ac97d05c8c5dc48b4d5b6f1992481cbbc661a87488611d3d513665a88dd3
          command: ["sh", "-c"]
          args: ["PLACEHOLDER"]
          volumeMounts:
            - {name: nas-media, mountPath: /media}
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {memory: 8Gi}
