---
apiVersion: batch/v1
kind: Job
metadata:
  name: PLACEHOLDER
  namespace: transcoding
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: drone-04
      volumes:
        - name: nas-media
          persistentVolumeClaim: {claimName: nas-media}
      containers:
        - name: handbrake
          image: ghcr.io/kevindurb/handbrake-cli:latest@sha256:0d7258515a138361bc5b0703c4231686448b88c9282bc4fab9a45208ecf127fb
          command: ["sh", "-c"]
          args: ["PLACEHOLDER"]
          volumeMounts:
            - {name: nas-media, mountPath: /media}
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {memory: 8Gi}
