---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo
namePrefix: forgejo-

resources:
  - ./deployment.yml

components:
  - ../../components/http-route-refs
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - forgejo.yml=gatus.yml
  - name: app-env
    literals:
      - USER_UID=1000
      - USER_GID=1000

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: forgejo
