---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo
namePrefix: forgejo-

resources:
  - ./deployment.yml

components:
  - ../../components/http-route-refs
  - ../../components/app-pod-hardening
  - ../../components/app-tmp-dirs

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: "true"
    files:
      - forgejo.yml=gatus.yml
  - name: app-env
    literals:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__SERVER__DOMAIN=forgejo.beaver-cloud.xyz
      - FORGEJO__SERVER__SSH_DOMAIN=git.beaver-cloud.xyz
      - FORGEJO__SERVER__SSH_PORT=22
      - FORGEJO__REPOSITORY__ENABLE_PUSH_CREATE_USER=true
      - FORGEJO__REPOSITORY__ENABLE_PUSH_CREATE_ORG=true

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: forgejo
