---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant
namePrefix: home-assistant-

resources:
  - ./home-assistant.yml

components:
  - ../../components/pod-hardening
  - ../../components/tmpdirs
  - ../../components/host-networking
  - ../../components/internal-http-route

replacements:
  - sourceValue: home-assistant.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - home-assistant.yml=gatus.yml
  - name: mosquitto-config
    files:
      - mosquitto.conf

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: home-assistant
