---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
      containers:
        - name: app
          image: docker.io/library/eclipse-mosquitto@sha256:a908c65cc8e67ec9d292ef27c2c0360dbaaee7eb1b935cdd194e67697f15dea1
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config
              readOnly: true
            - name: volume
              mountPath: /mosquitto/data
          resources:
            requests:
              memory: 32M
            limits:
              memory: 128M
          livenessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 5
            periodSeconds: 30
          ports:
            - name: mqtt
              containerPort: 1883

---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
