---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: alertmanager
spec:
  encryptedData:
    watchdog-url: AgC9VUqzmOlP9XjX7XAdjog379BR831KggsTectICU2LR941P3EpwKGoOzMN/Foh8lPGV3RS6txyUIBHtvyDM1Dr6lAxZB/3cg2Qhv0fnely2jIKD2mXEYEmw4ynsQ394hmf4a/8K09Xf+hi0UvwLaQOY0EOkNNultKXjDoYg8+Cr/Y+66NBbctz/Qv2xjXSk3nsqJyZD9A/8WBbO113GsaIZjLTea4hWdOqKco3OiBml92LwLPtz0lq1e1ZGgjeQIpuUi2jP29VK3EXZEpjaswn37CcuzAgBCSfxZ5wRNYSTlhXt96laOcX4GGFiajW+wEirA2O3GzgRqOuPI/QeH7JGLdAywVjIoYshOvGxe1O5A2D9IJGYUQuEY1bB0gDpiIZqTWXWzKdtgjYGjqQUk32xrWWQJRQ26fTaJDuDjNIgTLiU5L/jNIx4+jeB44ks+KYcXWu5wN4OlmTTsf8LJWDjtMvw+++VCP3d9SaWCtyajcEMj5i919Ji2FnCZF+TIXUZhRbnLiMM/V/gg2aMqHnwAfCjSdfsxemk+jEoO90IsQnup7XUg1thpv4MTu33asdluITwQy15H57TbJXYkBH1t6TodYl9Rwm4ACOSPXFPdqQt8/iGAbcUIokGp3ZnnXZ1KuWuU72bZFZwRHZD1IDb8b+ixtIwmgFKFTdXHQl0GjzlPGDozD3obj1LpLO2wtWUlDaqOoeEDxRTh/uq5vNp+ZRlbSCJ8WxkHSGCXkpdTI2xlEnYWMsRYtz67t4EJZvLJA=
