---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: &labels
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      hostname: alertmanager
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: app-volume
        - name: config-volume
          configMap:
            name: config
        - name: alertmanager-secret
          secret:
            secretName: alertmanager-secret
      containers:
        - name: alertmanager
          image: docker.io/prom/alertmanager@sha256:e9733bafb1bdef9b00e25a21f8f99dc26a22224bf16641ad754d1649f4c3357a
          resources:
            requests:
              memory: 50M
            limits:
              memory: 500M
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.external-url=https://alertmanager.beaver-cloud.ts.net
          env:
            - name: TZ
              value: America/Denver
          envFrom: []
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: data-volume
              mountPath: /alertmanager
            - name: alertmanager-secret
              mountPath: /run/secrets/webhook_url
              subPath: watchdog-url
              readOnly: true
          ports:
            - name: http
              containerPort: 9093

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    tailscale.com/proxy-group: ingress-proxy-group
    tailscale.com/tags: tag:k8s,tag:monitoring
spec:
  defaultBackend:
    service:
      name: app-service
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts: [alertmanager]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-volume
  labels:
    app.kubernetes.io/component: app
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: zfs-generic-nvmeof-csi
  resources:
    requests:
      storage: 1G
