---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: &labels
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      hostname: alertmanager
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: app-volume
        - name: config-volume
          configMap:
            name: config
        - name: alertmanager-secret
          secret:
            secretName: alertmanager-secret
      containers:
        - name: alertmanager
          image: docker.io/prom/alertmanager@sha256:58e117eabccebbff04e6643a3432d6315a2cc3a8c24ab5849bc628886bf08857
          resources:
            requests:
              memory: 50M
            limits:
              memory: 500M
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.external-url=https://alertmanager.beaver-cloud.xyz
          env:
            - name: TZ
              value: America/Denver
          envFrom: []
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: data-volume
              mountPath: /alertmanager
            - name: alertmanager-secret
              mountPath: /run/secrets/webhook_url
              subPath: watchdog-url
              readOnly: true
          ports:
            - name: http
              containerPort: 9093

---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: secret
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  organizationId: 575f69b2-49f4-456d-bd6f-b14101103188
  secretName: alertmanager-secret
  map:
    - secretKeyName: watchdog-url
      bwSecretId: 9eb00cb7-2014-4c70-9f76-b3fd00eda2f0
  authToken:
    secretName: bw-auth-token
    secretKey: token
