FROM quay.io/fedora/fedora-minimal:43

RUN dnf install -y \
  ansible \
  && dnf clean all

RUN mkdir /ansible
WORKDIR /ansible

COPY ./*.yml ./
COPY ./inventory ./inventory
COPY ./roles ./roles
COPY ./ansible.cfg ./

ENTRYPOINT [ "/usr/bin/ansible-playbook" ]
