FROM quay.io/fedora/fedora-minimal@sha256:791075c4569d28947bf9ef182352024d288ccc02f014873ad308ab035a6ba2dc

RUN dnf install -y \
  ansible \
  && dnf clean all

RUN mkdir /ansible

COPY ./*.yml /ansible/
COPY ./inventory /ansible/inventory
COPY ./roles /ansible/roles
COPY ./ansible.cfg /ansible/ansible.cfg

ENTRYPOINT [ "/usr/bin/ansible-playbook" ]
