default:
  @just --list

ansible *args:
  ansible -i ./inventory/prod.yml {{args}}

playbook *args:
  ansible-playbook -i ./inventory/prod.yml {{args}}

adhoc module filter='all':
  just ansible -m {{module}} {{filter}}

sudo-adhoc module filter='all':
  just ansible -b -m {{module}} {{filter}}

ping filter='all':
  just adhoc ping {{filter}}

reboot filter='all':
  just sudo-adhoc reboot {{filter}}

shutdown filter='all':
  just sudo-adhoc community.general.shutdown {{filter}}
