---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./home-assistant/app.yml
  - ./jellyfin/app.yml
  - ./syncthing/app.yml
  - ./template/app.yml
  - ./scrypted/app.yml
  - ./nextcloud/app.yml
