---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: syncthing
namePrefix: syncthing-

resources:
  - ./syncthing.yml

components:
  - ../../components/pod-hardening
  - ../../components/tmpdirs
  - ../../components/host-networking
  - ../../components/http-route

replacements:
  - sourceValue: syncthing.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - syncthing.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: syncthing
