---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: smartctl-exporter-
namespace: smartctl-exporter

resources:
  - ./smartctl-exporter.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: smartctl-exporter
