---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless-ngx
namePrefix: paperless-ngx-

resources:
  - ../../bases/valkey
  - ./paperless-ngx.yml

components:
  - ../../components/nas-media
  - ../../components/http-route

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - paperless-ngx.yml=gatus.yml

replacements:
  - sourceValue: paperless.beaver-cloud.xyz
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: paperless-ngx
