---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: &labels
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      volumes:
        - name: nas-media
          persistentVolumeClaim:
            claimName: nas-media
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
        - name: app
          image: lscr.io/linuxserver/calibre:latest@sha256:210dc050f7473197109fdc76f3809e9295566d68d2737363e60b1fc5fe170398
          env:
            - name: TZ
              value: America/Denver
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          envFrom: []
          volumeMounts:
            - name: nas-media
              mountPath: /eBooks
              subPath: eBooks
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: 128M
            limits:
              memory: 2G
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels: &labels
    app.kubernetes.io/component: app
spec:
  selector: *labels
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: internal-route
  annotations:
    internal-dns.alpha.kubernetes.io/target: internal.beaver-cloud.xyz
spec:
  parentRefs:
    - name: internal-beaver-cloud
      namespace: envoy-gateway-system
  hostnames:
    - calibre.beaver-cloud.xyz
  rules:
    - backendRefs:
        - name: app-service
          port: 80
