---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calibre
namePrefix: calibre-
resources:
  - ./deployment.yml
components:
  - ../../components/http-route-refs
configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - calibre.yml=gatus.yml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: calibre
