---
name: Check Kustomize
on:
  schedule:
    - cron: '05 10 * * 0' # 10:05am UTC Sunday
  push:
    branches:
      - main
    paths:
      - apps/**
      - platform/**
      - infrastructure/**
      - clusters/**
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: Check Kustomize
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: alexellis/arkade-get@master
        with:
          kustomize: latest

      - name: Check Kustomize
        run: |
          # shellcheck disable=SC2227
          find apps platform infrastructure clusters -name "kustomization.y*ml" -execdir kustomize build . > /dev/null \;

      - name: Connect to tailnet
        uses: tailscale/github-action@v4.2.0
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci
          ping: argocd

      - name: Trigger Argo CD refresh
        env:
          REV: ${{ github.event.head_commit.id }}
        run: |
          repo='https://github.com/kevindurb/k8s'
          curl -fsS -X POST https://argocd.beaver-cloud.ts.net/api/webhook \
            -H 'Content-Type: application/json' \
            -H 'X-GitHub-Event: push' \
            -d @- <<EOF
          {"repository": {"html_url": "$repo", "clone_url": "$repo.git"}, "after": "${REV:-0000000000000000000000000000000000000000}"}
          EOF
